name: Capstone check

on:
  push:
  pull_request:

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run check.py
        run: python labs/capstone/check.py
